### ISSUE TITLE
Projekt zarabia

### ISSUE THREAD

**Issue by ikurek** [asmonix/Rychu-PEA-3#1]
# Issue
Boli mnie, że Rychu Peja może w końcu uczciwie zarobić

# Steps to reproduce
None

**Comment by Shandelier** [comment]
Hello Igor!
Thanks for reporting this issue. I'm sorry to hear that it's aching you that Rychu can make a profit.

# I hope this will fix your problem: 
<details>
Znasz mnie lepiej niż ja siebie? 
Widziałeś mnie na glebie? 
Znasz upadek i cierpienie? 
Znasz każde wydarzenie, 
Które miało wpływ na mnie? 
Znasz mnie lepiej niż ja klaunie? (kłamiesz) 
Chcesz, by twa wyobraźnia mogła cię oszukać?
Znać P to sztuka, wystarczy P posłuchać, 
Przeczytać jeden wywiad, porozmawiać prywatnie 
P nie chce się zwierzać 
A to kurwa nie ładnie, 
P nie robi uczciwie, 
P bankowo nadal kradnie. 
Nie ważne że robota jest trudna,
Nie ogarnę tego wszystkiego naraz, 
Nie wyrobie się zaraz, 
Nie lubisz bakterii, 
Bo mnie nie znasz nie od dzisiaj, 
Wiem, że w tobie Rychu Peja nie znajdzie kibica 
Jak mnie to nie zachwyca 
Śmieszą teorie mętu, 
Ty znasz Rycha Peję 
Już na samym wejściu 
Ma być struty, bo zarzuty, 
Które padną są prawdą?
Gadaj zdrów, wiem kim jestem, 
Więc złoczyńcy odpadną!
Na to źle nie życzę, 
Wypierdalaj, nie krzyczę 
Spokojnie na tym bicie 
Ze słowami w zeszycie. 
Opowiadam jak widzicie 
Rycha Peję ja się śmieję. 
W niekorzystnym świetle 
Stawiać chcą poryte dekle, 
Żal ci dupę ściska,
Tylko na tym znasz się biegle 
Wbijać szpilę, głodne wilki 
Chcące pożreć Okuckiego 
Weź odpierdol się od niego 
A nie będzie boju tego... 
Odpierdol się od niego, nie będzie boju tego.. 

Ref. 
Co cię boli? 
Czy aż tak cię to boli, 
Że Rychu Peja ma szansę 
Dziś uczciwie zarobić? 
Przyjemne z pożytecznym, 
Pasja życiowa rap, 
Ja za ciebie nic nie zrobię 
A ty dziobem "kłap kłap".
Nierobie pierdolony, 
Zawistny Polaku, 
Zacznij zmieniać swoje życie, 
Jak nie chcesz żreć ochłapów, 
Zrób coś! Słyszysz? Zacznij żyć własnym życiem, 
Kłapnij jeszcze raz usłyszysz o tym na płycie!
(Hej! Ty! Wy! Oni!) 
(Co was boli? 
Co was kurwy boli?) 

Zauważasz sprzedaż płyt, 
Nie widzisz potu na skroni,
Widzisz w koło wielu ludzi, 
P sam się musi chronić, 
Sam się musi bronić,
Sam muzykę robić, 
Nikomu się nie żalić, 
Tylko dbać o swój interes, 
A czy wiesz że rap nim nie jest? 
Nie wiesz? Przecież znasz mnie. 
Spytaj czego nie słyszałem, 
Znajdź taką płytę, 
Znam całą klasykę, 
Zbyt długo w tym siedzę, 
Ty z mamusią przy obiedzie, 
A ja w sklepie hajs ostatni, 
Na oryginał CD'ek wydawałem,
Punkt dodatni. 
Śmiejesz się zgadnij, 
Kto się będzie śmiał ostatni, 
Śmiejesz się zgadnij, 
Śmiejesz się zgadnij, 
Gdzie prawdziwi słuchacze. 
Te twardziel co masz pod maską? 
Zapierdolę ci gonga, 
Jak Planet Asia Z Rasco,
Dla skurwysynów fiasko 
Ku uciesze ich lasek. 
Każda z nich z bajecznym tyłkiem, 
Zgrabną nóżką na obcasie, 
Węszy kasę, szczerzy zęby, 
Kocha w Peji się, wdzięczy 
Chcecie dupeczki bym waszych fake’ów wyręczył! 
Pozdrawiam kozaków, 
Na majkach niszczących łachów, 
Zniechęcajmy ich do rapu 
Zniechęcajmy.. Zniechęcajmy... 
Wtedy jeszcze bardziej będą nienawidzić 
Tych wszystkich, którym się udało przebić, 
Lirycznie robią wszystkich, 
Chcesz się wybić dla korzyści? 
Jesteś bez szans 
P styl ma ten sam, 
Nie zbiedniej jak Greg Nice 
Nie wiesz kto to taki? 
No to nie rób se jaj 
Za brak podstawowej wiedzy 
Weźmiesz szajs a nie hajs 
Oto Rycha postulat 
Nie ma się co rozczulać 
Jak z faktu że Swayze zapuszkował Ja Rule’a 
Jak z faktu że Swayze zapuszkował Ja Rule’a 

Ref. 
Co cię boli? 
Czy aż tak cię to boli, 
Że Rychu Peja ma szansę 
Dziś uczciwie zarobić? 
Przyjemne z pożytecznym, 
Pasja życiowa rap, 
Ja za ciebie nic nie zrobię, 
A ty dziobem "kłap kłap" 
Nierobie pierdolony, 
Zawistny Polaku, 
Zacznij zmieniać swoje życie, 
Jak nie chcesz żreć ochłapów. 
Zrób coś! Słyszysz? Zacznij żyć własnym życiem 
Kłapnij jeszcze raz usłyszysz o tym na płycie 

To mój rap... 
To moja rzeczywistość... 
Jakie życie, taki rap... 
W nim zawarte jest wszystko... 
Więc weź to wreszcie pojmij.. 
Jarzysz? Jarzysz? Kurwa jarzysz? [x2]
</details>
